### ISSUE TITLE
Inca_barracks have wrong civ (maya)

### ISSUE THREAD

**Issue by mrlie58** [wltonlopes/incas_0ad#10]
WARNING: The "structures/inca_barracks" template has a defined civ of "maya". This does not match the currently selected civ "inca".

**Comment by wltonlopes** [comment]
Thanks for the messages I will correct them today. I don't use this
email much, maybe messages like this are better for personal forum
messages.


Em Ter, 14 de jul de 2020 11:01 AM, mrlie58 <notifications@github.com>
escreveu:

**Comment by wltonlopes** [comment]
Thanks for the warnings I will correct today
